Secure Armory lockers
TS-Rogue-Star/Rogue-Star pull request #207
Opened 2024-04-04 00:47 UTC by Poojawa

It's weird actually getting BOTH of my projects done super quick. holy heck.

🆑 Poojawa
rscadd: Added Secured Armory Gun Lockers, death to racks.
/:cl:

![f574b4cdd9317f262cde8a416272b627](https://github.com/TS-Rogue-Star/Rogue-Star/assets/6293118/d869daac-3165-46da-9e7f-b9cac06ce8f0)

Lockable, toggleable, with sprites that let you see what's in them, as well as the ammunition currently remaining. 

Simply click a slot with a compatible gun in your hand to load it into the slots. 

I've tried to match the used sprite with an appropriate sized locker. Long arms are your rifles and shotguns. Side arms are the pistol-sized sprites.

Not every sprite is unique, I couldn't be arsed to sprite like 9 revolver alternatives for every type, but if someone wishes to, go for it! The locker dmi has templates to assist in the general 'size limit' for a given container's sprites. 

The lockers can be broken open with an energy sword, a welding tool, or an Emag. 

...I'll figure out how to let engineering fix broken doors eventually. but so far it works and I'm just happy to have it out there for code review.

Not mapped in yet, and I'll need to fiddle and see if I can make them scoop inventory on mapload only. 

You need armory access to open it, obviously.

2024-04-20 19:58 UTC, Arokha requested changes
Just a few minor things needed based on staff feedback.

Please change the 'vorestation' edit stuff and _vr file to rogue star instead (and _rs, don't forget to update the .dme too).

Document the access change made as well in the description.

2024-04-20 19:58 UTC, Arokha commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +
Might be nice if these got moved into a function instead of repeated here.
Why `else` then `if` instead of just a normal `elseif`?

2024-04-20 19:58 UTC, Arokha commented on code/modules/projectiles/gun_vr.dm
> +	overlay_type = "saber"
hey thats u

2024-04-20 19:58 UTC, Arokha commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +	req_one_access = list(access_explorer,access_armory)
Access change not mentioned in PR description.

Staff have approved this change now but make sure to put it in the description if you change stuff like that, as it reflects poorly if it appears hidden as it does in this case.

2024-04-20 19:58 UTC, Arokha commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +		add_overlay("door_openold") //VOREStationEDIT all of these should be considered 'old' sprites, but keep backwards compatability.
Not vorestation

2024-04-20 19:58 UTC, Arokha commented on code/modules/projectiles/gun_vr.dm
> +//Gun classifications for locker sanity
Discussed with others, decided that rogue star stuff should have _rs instead of _vr so it's more obvious what came from where.

2024-04-25 13:33 UTC, Arokha commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +	req_one_access = list(access_explorer,access_armory)
You marked it as resolved, but didn't add anything about it to the description?

2024-04-25 13:47 UTC, Poojawa commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +	req_one_access = list(access_explorer,access_armory)
Because it's been removed as a change?

2024-05-05 11:10 UTC, Very-Soft requested changes
Conflicts

2024-05-05 11:16 UTC, Poojawa commented
was expected, Recompiling now

2024-05-05 11:40 UTC, Very-Soft commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +				to_chat(usr, "<span class='notice'[src] doors are closed.</span>")
missing closing > on span class

2024-05-05 11:40 UTC, Very-Soft commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +				to_chat(usr, "<span class='notice'[src] doors are closed.</span>")
Also here, etc etc etc

2024-05-05 11:44 UTC, Very-Soft commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +		tgui_interact(user)
Not mandatory or anything, but as a game feel thingy, if you close the tgui menu and then click the locker to close it, it opens the menu again to show you the guns you can no longer pull out. Might be better if it did tgui after toggling, and only did tgui if it was open. Just a suggestion.

2024-05-05 11:55 UTC, Poojawa commented on code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
> +		tgui_interact(user)
Actually easily done and implimented!

2024-05-05 12:09 UTC, Very-Soft approved these changes

2024-05-05 12:10 UTC, merged