Journalist Time
TS-Rogue-Star/Rogue-Star pull request #670
Opened 2024-11-23 03:46 UTC by Lilly-Lira

Adds a Centcom Journal Role!

2024-11-24 04:13 UTC, lm40 requested changes
Probably the /datum/job/centcom_officer/get_access() should be /datum/job/centcom_journalist/get_access()

2024-11-24 04:20 UTC, lm40 commented
Or actually on second thought maybe make this whole thing a subtype of centcom_officer unless you have some compelling reason it should be different

2024-12-07 04:39 UTC, Lilly-Lira commented
It is efficient now :3

2024-12-07 05:03 UTC, lm40 approved these changes

2024-12-07 05:23 UTC, merged