[DNM] AutoTransfer Vore Panel
TS-Rogue-Star/Rogue-Star pull request #701
Opened 2024-12-08 02:16 UTC by Lilly-Lira

Adds autotransfer options to the vore panel.  Early WIP!

2024-12-08 22:09 UTC, Screemonster commented
okay so while you're in this thing adding stuff to the vore panel and save files

#536 and #603 have a bunch of vars added to bellies that aren't on the save/panel and it would be good to add them

2025-03-30 07:20 UTC, Lilly-Lira commented
> okay so while you're in this thing adding stuff to the vore panel and save files
> 
> #536 and #603 have a bunch of vars added to bellies that aren't on the save/panel and it would be good to add them

To keep things modular, I'll leave that out of this PR, but I'll add that to my todo list!

2025-03-30 12:28 UTC, Very-Soft requested changes
conflicts

2025-04-06 16:56 UTC, Lilly-Lira commented
Conflicts fixed!  Also did further adjustment to make simple mobs work correctly with the updates

2025-04-06 17:34 UTC, merged